# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: aiagent-workshop
hooks:
  preup:
    posix:
      shell: sh
      run: chmod u+r+x ./scripts/validate_env_vars.sh; ./scripts/validate_env_vars.sh
      interactive: true
      continueOnError: false
    windows:
      shell: pwsh
      run: ./scripts/validate_env_vars.ps1
      interactive: true
      continueOnError: false
  # preprovision:
  #   posix:
  #     shell: sh
  #     run: chmod u+r+x ./scripts/set_default_models.sh; chmod u+r+x ./scripts/resolve_model_quota.sh; ./scripts/set_default_models.sh
  #     interactive: true
  #     continueOnError: false
  #   windows:
  #     shell: pwsh
  #     run: ./scripts/set_default_models.ps1
  #     interactive: true
  #     continueOnError: false
  postprovision:
    windows:
      shell: pwsh
      run: ./scripts/write_env.ps1;
      continueOnError: true
      interactive: true
    posix:
      shell: sh
      run: chmod u+r+x ./scripts/write_env.sh; chmod u+r+x ./scripts/write_env.sh;
      continueOnError: true
      interactive: true

pipeline:
  variables:
services:
  api:
    project: ./src/backend/ContosoBikestore.Agent.Host
    language: csharp
    host: appservice
  contoso-store-api:
    project: ./src/backend/ContosoBikestore.API
    language: csharp
    host: appservice
  contoso-store-mcp:
    project: ./src/backend/ContosoBikestore.MCPServer
    language: csharp
    host: appservice
  # web:
  #   project: ./src/frontend
  #   dist: .next/standalone/src/frontend
  #   language: ts
  #   host: appservice
  #   hooks:
  #     prebuild:
  #       windows:
  #         shell: pwsh
  #         run: 'echo "BACKEND_AGENT_BASE_URL=`"$env:BACKEND_APP_URL/agent`"" > .env.local ; echo "APPLICATIONINSIGHTS_CONNECTION_STRING=`"$env:AZURE_APP_INSIGHTS_CONNECTION_STRING`"" >> .env.local'
  #       posix:
  #         shell: sh
  #         run: 'echo BACKEND_AGENT_BASE_URL=\"$BACKEND_APP_URL/agent\" > .env.local && echo APPLICATIONINSIGHTS_CONNECTION_STRING=\"$AZURE_APP_INSIGHTS_CONNECTION_STRING\" >> .env.local'
  #     postbuild:
  #       windows:
  #         shell: pwsh
  #         run: '../../scripts/copy-standalone-files.ps1; echo "# Include all files in standalone deployment`n!*`n!node_modules/`n!.next/" > .next/standalone/src/frontend/.deployignore'
  #         continueOnError: false
  #       posix:
  #         shell: sh
  #         run: 'sh ../../scripts/copy-standalone-files.sh && echo "# Include all files in standalone deployment\n!*\n!node_modules/\n!.next/" > .next/standalone/src/frontend/.deployignore'
  #         continueOnError: false
  #     prepackage:
  #       windows:
  #         shell: pwsh
  #         run: 'echo "BACKEND_AGENT_BASE_URL=`"$env:BACKEND_APP_URL/agent`"" > .env.local ; echo "APPLICATIONINSIGHTS_CONNECTION_STRING=`"$env:AZURE_APP_INSIGHTS_CONNECTION_STRING`"" >> .env.local'
  #       posix:
  #         shell: sh
  #         run: 'echo BACKEND_AGENT_BASE_URL=\"$BACKEND_APP_URL/agent\" > .env.local && echo APPLICATIONINSIGHTS_CONNECTION_STRING=\"$AZURE_APP_INSIGHTS_CONNECTION_STRING\" >> .env.local'
  #     postdeploy:
  #       windows:
  #         shell: pwsh
  #         run: "rm .env.local"
  #       posix:
  #         shell: sh
  #         run: "rm .env.local"
